### PR TITLE
Fail step when request fails and added an input to fail the step when a specific response code is returned.

### PR DESCRIPTION
**Pull request by geekkoz**
- Added check to fail the step when curl request fails.
- Added logic to include option to fail step when specific response code is returned.

### CODE REVIEW

**Comment by teameh** [comment]
Hi @geekkoz,

Sorry for my late response.. 

Could you explain why you would need this?

**Comment by geekkoz** [comment]
Hello @teameh ,

There are some cases where posting to BB server fails due server unavailable for maintenance or something else but the step is count as succeed when this should have failed as status could not be posted, so, the idea is that we can add a response code that can be handled as step fail so we can retry the step and not the entire pipeline.

I hope this make it a little bit more clear :)

**Comment by teameh** [comment]
Hi @geekkoz, so currently the step will look like a success if bitbucket is unavailable?

**Comment by geekkoz** [comment]
@teameh actually it was meant to do the opposite, fail the step ig 302 or any other, at the moment the step marks as success and then we would need to retry the entire pipeline for getting a BB build update, but with this we would only need to retry this step only in that case.

**Comment by ArtuGuiAdi** [comment]
We are experiencing the same problem, and the proposed solution would work for us. Could we reopen this PR?

**Pull request closed without merging**
